platform :ios, '9.0'

install! 'cocoapods',
           :deterministic_uuids => false

target 'ios' do
  use_frameworks!
  pod 'j2objclib', :path => '../app'
end

target 'iosTestOnly' do
  use_frameworks!
  pod 'testj2objclib', :path => '../app'
end

target 'iosTestOnlyTests' do
  use_frameworks!
  pod 'testj2objclib', :path => '../app'
end
